---
# tasks file for icinga

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: icinga

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: icinga

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: icinga

- include: FreeBSD.yml
  when: ansible_distribution == "FreeBSD"
  tags: icinga

- name: Create Icinga configuration file
  template: >
    src=icinga2.conf.j2
    dest=/etc/icinga2/icinga2.conf
    owner=root
    group=root
    mode=0644
  notify: restart icinga
  tags: icinga

- name: Ensure Icinga service is started and enabled on boot
  service: name={{ icinga_service_name }} state=started enabled=yes
  tags: icinga
